language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pratyush/docker-react -f Dockerfile.dev .

#Create React App, we need to make a small modification:
#script:
# - docker run USERNAME/docker-react npm run test -- --coverage
#instead should be:
#script:
#  - docker run -e CI=true USERNAME/docker-react npm run test
#travis build fails with “rakefile not found”
#adding to the top of your .travis.yml file:
#language: generic 

#older script section
#script:
#  - docker run pratyush/docker-react npm run test -- --coverage

script:
  - docker run -e CI=true pratyush/docker-react npm run test